### ISSUE TITLE
I am facing problems when it comes to requesting data from database.

### ISSUE THREAD

**Issue by Dev-Aspect** [AntonGlyzin/myshopbot#1]
I ran bot.py and got this error message.

```
2022-11-01 16:55:20,044 (__init__.py:964 MainThread) ERROR - TeleBot: "Infinity polling exception: (sqlite3.OperationalError) no such table: product
[SQL: SELECT product.id AS product_id, product.title AS product_title, product.photo AS product_photo, product.description AS product_description, product.price AS product_price, product.currency AS product_currency, product.quantity AS product_quantity, product.is_active AS product_is_active 
FROM product 
WHERE product.is_active = 1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)"
2022-11-01 16:55:20,044 (__init__.py:966 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 959, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1047, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1122, in __threaded_polling
    raise e
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1078, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 154, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 98, in run
    task(*args, **kwargs)
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 6084, in _run_middlewares_and_handler
    result = handler['function'](message, bot=self)
  File "D:\A new bot\myshopbot-main\handlers.py", line 88, in shop_list_product
    query = session.query(Product).filter(Product.is_active).all()
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\query.py", line 2772, in all
    return self._iter().all()
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\query.py", line 2907, in _iter
    result = self.session.execute(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Shahriyor (10G)\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: product
[SQL: SELECT product.id AS product_id, product.title AS product_title, product.photo AS product_photo, product.description AS product_description, product.price AS product_price, product.currency AS product_currency, product.quantity AS product_quantity, product.is_active AS product_is_active 
FROM product 
WHERE product.is_active = 1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

What should I do?

**Comment by AntonGlyzin** [comment]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: product

**Comment by xsa-dev** [comment]
readme don't provide commands for creating db.. ☹️

**Comment by AntonGlyzin** [comment]
> readme don't provide commands for creating db.. frowning_face

I was hoping that the people who will run the project are familiar with alembic and sqlalchemy
but later I added a section - how to configure the database(Настройка БД)
